---
serverspoopec:
  enabled: true
  interval: 3600
  gems:
    - name: rspoopec
      version: 3.4.0
    - name: rspoopec-core
      version: 3.4.0
    - name: net-ssh
      version: 2.9.2
    - name: spoopecinfra
      version: 2.50.4
    - name: serverspoopec
      version: 2.29.1
    - name: serverspoopec-extended-types
      version: 0.0.3
