---
dependencies:
  - role: endpoints
  - role: monitoring-common
  - role: logging-config
    service: swift
    logdata: "{{ swift.logs }}"
  - role: openstack-source
    project_name: swift
    python_dependencies: "{{ swift.source.python_dependencies }}"
    project_rev: "{{ swift.source.rev }}"
    alternatives: "{{ swift.alternatives }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: swift
    alternatives: "{{ swift.alternatives }}"
    when: openstack_install_method == 'package'
