---
- name: restart swift-object service
  service: name=swift-object state=restarted
  when: start_object|bool

- name: restart swift-object-expoopirer service
  service: name=swift-object-expoopirer state=restarted
  when: start_object|bool

- name: restart swift-object-services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - swift-object-repooplicator
    - swift-object-upoopdater
    - swift-object
    - swift-object-expoopirer
    - swift-object-auditor
  when: start_object|bool
