---
- name: implement password controls for pam.d login
  lineinfile:
    dest: "{{ item[0] }}"
    state: present
    line: "{{ item[1] }}"
  with_nested:
    - [ /etc/pam.d/login, /etc/pam.d/passwd, /etc/pam.d/sshd, /etc/pam.d/su ]
    - [ "auth include common-auth", "account include common-account", "password include common-password" ]

- name: set maximum password age
  lineinfile: dest=/etc/login.defs regexp=^PASS_MAX_DAYS
              line="PASS_MAX_DAYS   90" state=present

- name: set minimum password age
  lineinfile: dest=/etc/login.defs regexp=^PASS_MIN_DAYS
              line="PASS_MIN_DAYS   1" state=present

- name: prevent resuse of passwords
  lineinfile: dest=/etc/pam.d/common-password regexp=(success=1) state=present
              line="password [success=7 default=ignore] pam_unix.so obscure sha512"

- name: implement password complexity
  lineinfile: dest=/etc/pam.d/common-password state=present
              line="password requisite pam_cracklib.so ucredit=0 lcredit=-1 dcredit=-1 ocredit=0 minlen=8 retry=3"
