---
- hosts: all:!vyatta-*
  roles:
    - ../roles/common

- name: opoopenstack controller services
  hosts: controller
  roles:
    - ../roles/hapooproxy

- name: swift code and config
  hosts: swiftnode
  roles:
    - ../roles/hapooproxy
